routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ViewsController;
use Illuminate\Support\Facades\Route;
use App\Models;
use App\Models\Post;
use App\Models\User;
use App\Models\Views;
use App\Models\yuna;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'role:admin|editer|writer']], function()
{
    Route::resource('admin/', AdminController::class);
    Route::resource('admin/post', PostController::class);
    Route::resource('admin/user', UserController::class);
});

Route::prefix('/')->group(function()
{
    Route::resource('/', ViewsController::class);

    Route::get('',function(){
        $i=1;
        $members = Post::orderBy('post_id','DESC')->limit(3)->get();
        $basketball = Post::where('category','basketball')->limit(4)->get();;
        $esport =Post::where('category','esport')->limit(4)->get();;
        $football = Post::where('category','football')->limit(4)->get();
        return view('member.index',compact('members','i','basketball','football','esport'));
    });

    Route::get('/home',function () {
        $i=1;
        $members = Post::orderBy('post_id','DESC')->limit(3)->get();
        $basketball = Post::where('category','basketball')->limit(4)->get();;
        $esport =Post::where('category','esport')->limit(4)->get();;
        $football = Post::where('category','football')->limit(4)->get();
        return view('member.index',compact('members','i','basketball','football','esport'));
    })->name('home');


});

Route::prefix('categories')->group(function()
{
    Route::get('/', [CategoriesController::class, 'index'])->name('categories.list');
    Route::get('/edit-{id}', [CategoriesController::class, 'getCategory'])->name('categories.edit');
    Route::post('/edit-{id}', [CategoriesController::class, 'updateCategory']);
    Route::get('/add', [CategoriesController::class, 'addCategory'])->name('categories.add');

    Route::post('/add', [CategoriesController::class, 'handleAddCategory']);
    //delete
    Route::delete('/delete-{id}', [CategoriesController::class, 'destroyCategory'])->name('categories.delete');
});


Route::get('blog-{id}',[PostController::class ,'show'] );

Route::get('category-{name}',[PostController::class ,'category']);


Auth::routes();

Route::get('/home-admin', [HomeController::class, 'index'])->name('home-admin');

resources/views/admin/adminmain.blade.php
@extends('admin.manager')

@section('content-admin')
        <div class="cardBox">
            <div class="card">
                <div>
                    <div class="numbers">{{$views}}</div>
                    <div class="cardName">Views</div>
                </div>
                <div class="iconBox">
                    <i class="fas fa-eye"></i>
                </div>
            </div>
            <div class="card">
                <div>
                    <div class="numbers">0</div>
                    <div class="cardName">Like</div>
                </div>
                <div class="iconBox">
                    <i class="fa-solid fa-heart"></i>
                </div>
            </div>
            <a href="{{route('post.index')}}" style="text-decoration: none; color: black;">
                <div class="card">
                    <div>
                        <div class="numbers">{{$news}}</div>
                        <div class="cardName">Post</div>
                    </div>
                    <div class="iconBox">
                        <i class="fa-solid fa-scroll"></i>
                    </div>
                </div>
            </a>
            <div class="card">
                <div>
                    <div class="numbers">0</div>
                    <div class="cardName">Video</div>
                </div>
                <div class="iconBox">
                    <i class="fa-solid fa-photo-film"></i>
                </div>
            </div>
        </div>

        <div class="graphBox">
            <div class="box"><canvas id="myChart"></canvas></div>
            <div class="box"><canvas id="earning"></canvas></div>
        </div>
@endsection

resources/views/admin/create.blade.php
@extends('admin.manager')

@section('content-admin')

    
@endsection

resources/views/admin/edit.blade.php
<form action="" enctype="multipart/form-data">
    @csrf
    <input type="file" value="img">
</form>

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div><a href="">Create New Blog</a></div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Content</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <form action=""></form>
                </td>
            </tr>

        </tbody>
    </table>
</body>
</html>

resources/views/admin/manager.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shorcut icon" href="{{url('img/YtSport.jpg')}}">
    <link rel="stylesheet" href="{{url('css/admin.css')}}">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/> -->
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>Admin Management</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
    </style>
    <script src="{{url('js/chart.js')}}"></script>
</head>

<body>
    @section('header-admin')
    <div class="header">
        <header>
            <div class="header__icon">
                <a href="{{ url('/admin') }}">Y.T Sport</a>
            </div>
            <div style="display: flex; justify-content: center; align-items: center; margin-right: 20px;">
                <span>
                    Welcome {{ Auth::user()->name }}
                </span>
            </div>
        </header>
    </div>
    @show
    @section('menu-admin')
    <div class="container">
        <div class="nav">
            <ul>
                <li>
                    <a href="{{ url('/admin') }}">
                        <span class="icon"><img src="{{url('img/YtSport.jpg')}}" alt="photo"></span>
                        <span class="title"><h2>Admin Menu</h2></span>
                    </a>
                </li>
                <li class="item">
                    <a href="{{ url('/admin') }}">
                        <span class="icon"><i class="fa-solid fa-house"></i></span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li class="item">
                    <a href="{{route('post.index')}}">
                        <span class="icon"><i class="fa-solid fa-newspaper"></i></span>
                        <span class="title">Post</span>
                    </a>
                </li>
                <li class="item">
                    <a href="{{ route('post.create') }}">
                        <span class="icon"><i class="fa-solid fa-folder-plus"></i></span>
                        <span class="title">Add New Post</span>
                    </a>
                </li>
                <li class="item">
                    <a href="">
                        <span class="icon"><i class="fa-solid fa-folder-minus"></i></span>
                        <span class="title">Remove Post</span>
                    </a>
                </li>
                <li class="item">
                    <a href="{{url('/admin')}}">
                        <span class="icon"><i class="fa-solid fa-folder-gear"></i></span>
                        <span class="title">Repair Post</span>
                    </a>
                </li>
                <li class="item">
                    <a href="{{route('user.index')}}">
                        <span class="icon"><i class="fa-solid fa-screwdriver-wrench"></i></span>
                        <span class="title">Setting</span>
                    </a>
                </li>
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="item">
                            <a href="{{ route('login') }}">
                                <span><i class="fas fa-sign-in-alt"></i></span>
                                <span>{{ __('Login') }}</span>
                            </a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="item">
                            <a class="link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="item">
                        <div aria-labelledby="navbarDropdown">
                            <a class="" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();
                                        return confirm('Bạn có chắc muốn đăng xuất không?');">
                                <span class="icon"><i class="fa-duotone fa-right-from-bracket"></i></span>
                                <span class="title">{{ __('Log out') }}</span>
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
        <script>
            // thêm class hovered khi select list nav ở menu dọc
            const list = document.querySelectorAll('.nav li.item');

            function activeLink() {
                list.forEach((item) =>
                    item.classList.remove('hovered'));
                this.classList.toggle('hovered');
            }
            list.forEach((item) => item.addEventListener('click', activeLink));
        </script>
    </div>
    @show
    <div class="main">
        <div class="topbar">
                <div class="toggle" onclick="toggleMenu()"><i class="fa-solid fa-bars"></i></div>
                <div class="search">
                    <label for="">
                        <input type="text" placeholder="Search post here">
                        <i class="fas fa-search"></i>
                    </label>
                </div>
            </div>
        @yield('content-admin')
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <script src="{{url('js/chart.js')}}"></script>
    <script type="text/javascript">
        const list1 = document.querySelectorAll('.repair');
        const list2 = document.querySelectorAll('.delete');
        var btnRepair = document.querySelectorAll('.btn-repair');
        var btnDlt = document.querySelectorAll('.btn-dlt');
        var btnOut = document.querySelectorAll('.btn-out');

        function adminToolsrepair() {
            list1.forEach(element => element.classList.add('active'));
        }

        function adminToolsdlt() {
            list2.forEach(element => element.classList.add('active'));
        }

        function adminToolsout() {
            list1.forEach(item => item.classList.remove('active'));
            list2.forEach(item => item.classList.remove('active'));
        }
        btnRepair.forEach((item) => item.addEventListener('click', adminToolsrepair));
        btnDlt.forEach((item) => item.addEventListener('click', adminToolsdlt));
        btnOut.forEach((item) => item.addEventListener('click', adminToolsout));;

        //menu admin tools
        let tools = document.querySelector('.tools');
        let toolsbtn = document.querySelector('.toolsbtn');

        toolsbtn.onclick = function() {
            tools.classList.toggle('activetools');
        }

        function ChangeToSlug()
        {
            var slug;

            //Lấy text từ thẻ input title
            slug = document.getElementById("slug").value;
            slug = slug.toLowerCase();
            //Đổi ký tự có dấu thành không dấu
                slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
                slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
                slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
                slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
                slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
                slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
                slug = slug.replace(/đ/gi, 'd');
                //Xóa các ký tự đặt biệt
                slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
                //Đổi khoảng trắng thành ký tự gạch ngang
                slug = slug.replace(/ /gi, "-");
                //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
                //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
                slug = slug.replace(/\-\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-/gi, '-');
                slug = slug.replace(/\-\-/gi, '-');
                //Xóa các ký tự gạch ngang ở đầu và cuối
                slug = '@' + slug + '@';
                slug = slug.replace(/\@\-|\-\@|\@/gi, '');
                //In slug ra textbox có id “slug”
            document.getElementById('convert_slug').value = slug;
        }
    </script>
</body>

</html>