routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ViewsController;
use Illuminate\Support\Facades\Route;
use App\Models;
use App\Models\Post;
use App\Models\User;
use App\Models\Views;
use App\Models\yuna;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'role:admin|editer|writer']], function()
{
    Route::resource('admin/', AdminController::class);
    Route::resource('admin/post', PostController::class);
    Route::resource('admin/user', UserController::class);
});

Route::prefix('/')->group(function()
{
    Route::resource('/', ViewsController::class);

    Route::get('',function(){
        $i=1;
        $members = Post::orderBy('post_id','DESC')->limit(3)->get();
        $basketball = Post::where('category','basketball')->limit(4)->get();;
        $esport =Post::where('category','esport')->limit(4)->get();;
        $football = Post::where('category','football')->limit(4)->get();
        return view('member.index',compact('members','i','basketball','football','esport'));
    });

    Route::get('/home',function () {
        $i=1;
        $members = Post::orderBy('post_id','DESC')->limit(3)->get();
        $basketball = Post::where('category','basketball')->limit(4)->get();;
        $esport =Post::where('category','esport')->limit(4)->get();;
        $football = Post::where('category','football')->limit(4)->get();
        return view('member.index',compact('members','i','basketball','football','esport'));
    })->name('home');


});

Route::prefix('categories')->group(function()
{
    Route::get('/', [CategoriesController::class, 'index'])->name('categories.list');
    Route::get('/edit-{id}', [CategoriesController::class, 'getCategory'])->name('categories.edit');
    Route::post('/edit-{id}', [CategoriesController::class, 'updateCategory']);
    Route::get('/add', [CategoriesController::class, 'addCategory'])->name('categories.add');

    Route::post('/add', [CategoriesController::class, 'handleAddCategory']);
    //delete
    Route::delete('/delete-{id}', [CategoriesController::class, 'destroyCategory'])->name('categories.delete');
});


Route::get('blog-{id}',[PostController::class ,'show'] );

Route::get('category-{name}',[PostController::class ,'category']);


Auth::routes();

Route::get('/home-admin', [HomeController::class, 'index'])->name('home-admin');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'content',
        'summary',
        'slug',
        'img_post',
        'post_view',
        'creator_id',
        'status',
        'category'
    ];

    protected $primaryKey = 'post_id';
    protected $table = 'post';
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\Types\Null_;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // public function __construct()
    // {
    //     $this->middleware('permission:edit articles', ['only' => ['index', 'show', 'edit']]);
    //     $this->middleware('permission:add articles', ['only' => ['index', 'store']]);
    //     $this->middleware('permission:delete articles', ['only' => ['index', 'destroy']]);
    //     $this->middleware('permission:publish articles', ['only' => ['index']]);
    // }

    public function index()
    {
        $news = Post::all();
        return view('admin.post.index')->with(compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'title' => 'required|max:255',
                'summary' => 'required|max:255',
                'slug' => 'required|unique:post',
                'content' => 'required|max:255',
                'img' => 'required|image|max:2048|mimes:jpg,png,jpeg,gif,svg'
            ],
            [
                'title.required' => 'Bạn chưa có tiêu đề bài viết',
                'summary.required' => 'Bạn chưa có mô tả',
                'slug.unique' => 'Slug này đã được sử dụng',
                'img' => 'Bạn chưa thêm ảnh hoặc ảnh quá nặng'
            ]
        );

        // $data2 = $request->all();
        // dd($data2);

        // if($request->has('img'))
        // {
        //     $file = $request->$img;
        //     $file_name = $file->getClient
        // }

        $post = new Post();
        $post->title = $data['title'];
        $post->content = $data['content'];
        $post->summary = $data['summary'];
        $post->slug = $data['slug'];

        $get_image = $request->img;
        $path = 'uploads/post';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.', $get_name_image));
        $new_name = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path, $new_name);

        $post->category = $request->input('category');
        $post->img_post = $new_name;
        $post->post_view = 0;
        $post->creator_id = 1;
        $post->status = 1;
        $post->save();

        return redirect()->back()->with('message', 'Them post thanh cong!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $detail = Post::find($id);
        $detail->post_view++;
        $detail->save();
        return view('member.show',compact('detail'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('admin.post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate(
            [
                'title' => 'required',
                'summary' => 'required',
                'slug' => 'required',

            ],
            [
                'title.required' => 'Bạn chưa có tiêu đề bài viết',
                'summary.required' => 'Bạn chưa có mô tả',
                'slug.required' => 'Slug này đã được sử dụng',

            ]
        );

        $post = Post::find($id);
        $post->title = $data['title'];
        // $post->content = $data['content'];
        $post->summary = $data['summary'];
        $post->slug = $data['slug'];

        $get_image = $request->img;
        if($get_image){
            $path = 'uploads/post';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.', $get_name_image));
            $new_name = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path, $new_name);
            $post->img_post = $new_name;
        }
        $post->category = $request->input('category');
        $post->content = $request->input('content');
        $post->post_view = 0;
        $post->creator_id = 1;
        $post->status = 1;
        $post->save();

        return redirect()->back()->with('message', 'Cập nhật bài viết thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $path = 'uploads/post'.$post->img_post;
        if(file_exists($path)){
            unlink($path);
        }
        Post::find($id)->delete();
        return redirect()->back()->with('message', 'Xoa post thanh cong!');
    }

    public function category($category)
    {
    //    $category = DB::table('members')->get()->where('name',$name);

       $category = Post::where('category',$category)->paginate(15);

       return view('member.category', ['category' => $category]);
    }

}

resources/views/admin/post/create.blade.php
@extends('admin.manager')

@section('content-admin')
<div class="form-create-post">
@hasanyrole('admin|writer')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    <h1 class="title-create-post">Tạo Post</h1>
    <form action="{{route('post.store')}}" method="POST" class="form-create-post-inside" enctype="multipart/form-data">
        @csrf
        <div class="form-create-item">
            <label for="" class="title-label">Tiêu đề Post</label>
            <input id="slug" class="title-input" type="text" name="title" placeholder="Tua de" onkeyup="ChangeToSlug()">
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Slug Post</label>
            <input id="convert_slug" class="title-input" type="text" name="slug" placeholder="Slug">
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Category</label>
            <select name="category">
                <option value="" default>Chọn thể loại tin tức:</option>
                <option value="basketball">Bóng rổ</option>
                <option value="football">Bóng đá</option>
                <option value="volleyball">Bóng chuyền</option>
                <option value="esport">Esport</option>
            </select>
        </div>
        <div class="form-create-item">
            <label for="">Mô Tả</label>
            <textarea class="title-input title-2" type="text" name="summary" placeholder="Mo ta" rows="4" style="resize: none;"></textarea>
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Nội Dung:</label>
            <textarea class="title-input title-2" name="content" cols="20" rows="7" placeholder="Nội dung" style="resize: none;"></textarea>
        </div>
        <div class="form-create-upload-file">
            <div>
                <input class="title-input upload-file" type="file" name="img">
            </div>
            <div class="btn-submit">
                <button type="submit">Lưu Post</button>
            </div>
        </div>
    </form>
@else
    <h1 style="display: flex; justify-content: center; align-items: center; color: #03a9f4;">Bạn không có quyền thêm bài viết</h1>
@endhasanyrole
</div>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.manager')

@section('content-admin')
<div class="form-create-post">
@hasanyrole('admin|edit')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    <h1 class="title-create-post">Sửa Post</h1>
    <form action="{{route('post.update', $post->post_id)}}" method="POST" class="form-create-post-inside" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-create-item">
            <label for="" class="title-label">Tiêu đề Post</label>
            <input id="slug" class="title-input" type="text" name="title" value="{{ $post->title }}" onkeyup="ChangeToSlug()">
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Slug Post</label>
            <input id="convert_slug" class="title-input" type="text" name="slug" value="{{ $post->slug }}">
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Category</label>
            <select name="category">
                <option value="" default>Chọn thể loại tin tức:</option>
                <option value="basketball">Bóng rổ</option>
                <option value="football">Bóng đá</option>
                <option value="volleyball">Bóng chuyền</option>
                <option value="esport">Esport</option>
            </select>
        </div>
        <div class="form-create-item">
            <label for="">Mô Tả</label>
            <textarea class="title-input title-2" type="text" name="summary" placeholder="{{ $post->summary }}" rows="4" style="resize: none;"></textarea>
        </div>
        <div class="form-create-item">
            <label for="" class="title-label">Nội Dung:</label>
            <textarea class="title-input title-2" name="content" cols="20" rows="7" placeholder="{{ $post->content }}" style="resize: none;"></textarea>
        </div>
        <div class="form-create-upload-file">
            <div style="display: flex; flex-direction: column;">
                <input class="title-input upload-file" type="file" name="img">
                <img src="{{asset('uploads/post/'.$post->img_post)}}" alt="photo" style="width: 150px; height: 150px; margin: 20px;">
            </div>
            <div class="btn-submit">
                <button type="submit">Lưu Post</button>
            </div>
        </div>
    </form>
@else
    <h1 style="display: flex; justify-content: center; align-items: center; color: #03a9f4;">Bạn không có quyền thêm bài viết</h1>
@endhasanyrole
</div>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.manager')

@section('content-admin')
<div class="details" style="grid-template-columns: 1fr; margin-top: 25px;">
    <div class="recentOrders">
        <div class="cardHeader">
            <h2>Recent Post/Bài viết hiện tại</h2>
        </div>
        <table>
            <thead>
                <tr>
                    <td>Thứ Tự</td>
                    <td>Tiêu Đề</td>
                    <td>Tóm Tắt</td>
                    <td>Ảnh</td>
                    <td>Lượt Xem</td>
                    <td>Tình Trạng</td>
                    <td>Ngày tạo</td>
                    <td>Ngày Sửa Cuối</td>
                    <td>Quản Lý</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($news as $key => $new)
                <tr>
                    <td>{{$key + 1}}</td>
                    <td>{{$new->title}}</td>
                    <td>{{$new->summary}}</td>
                    <td><img style="width: 40px; height: 40px;" src="{{url('uploads/post').'/'.$new->img_post }}" alt="photo"></td>
                    <td>{{$new->post_view}}</td>
                    <td>
                        @if ($new->status == 0)
                            <span class="status return">Return</span>
                        @elseif($new->status == 1)
                            <span class="status delivered">Delivered</span>
                        @else
                            <span class="status pending">Pending</span>
                        @endif
                    </td>
                    <td>
                        <?php
                            $daytime  = $new->created_at;
                            $day = explode(" ", $daytime);
                            echo $day[0];
                        ?>
                    </td>
                    <td>
                        <?php
                            $daytime  = $new->updated_at;
                            $day = explode(" ", $daytime);
                            echo $day[0];
                        ?>
                    </td>
                    <td>
                        <form action="{{route('post.destroy',[$new -> post_id])}}" method="POST"  style="margin-bottom: 10px;">
                            @method('DELETE')
                            @csrf
                            <button style="border: 2px solid #03a9f4;" class="btn btn-manager" onclick="return confirm('Bạn có chắc muốn xóa {{$new->title}} này không?');">DELETE</button>
                        </form>
                        <a href="{{route('post.edit',[$new -> post_id])}}" class="btn btn-manager">REPAIR</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection